function tracks = initializeTracks()
        % create an empty array of tracks
        tracks = struct(...
            'id', {}, ...
            'bbox', {}, ...
            'bboxHist', {}, ...
            'xMotion', {}, ...
            'yMotion', {}, ...
            'currPerson', '',...
            'personCount', {},...
            'time', {},...
            'kalmanFilter', {}, ...
            'age', {}, ...
            'totalVisibleCount', {}, ...
            'consecutiveInvisibleCount', {});
    end